[build]
  command = "npm run build"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg", "puppeteer-core", "@sparticuz/chromium"]

[functions."*"]
  # garante que os assets dos certificados v√£o junto no deploy das Functions
  included_files = ["public/cert-templates/**", "public/images/**"]

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/webhooks/stripe"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
