[build]
  command = "echo build-skip"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/webhooks/stripe"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
